/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Billing details of the account holder.
*/
export class ACHBillingDetails {
    /**
    * Full name of the card or bank account holder.
    */
    'name': string;
    /**
    * City portion of the address.
    */
    'city'?: string;
    /**
    * Country portion of the address. Formatted as a two-letter country code specified in ISO 3166-1 alpha-2.
    */
    'country'?: string;
    /**
    * Line one of the street address.
    */
    'line1'?: string;
    /**
    * Line two of the street address.
    */
    'line2'?: string;
    /**
    * State / County / Province / Region portion of the address. If the country is US or Canada, then district is required and should use the two-letter code for the subdivision.
    */
    'district'?: string;
    /**
    * Postal / ZIP code of the address.
    */
    'postalCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "line1",
            "baseName": "line1",
            "type": "string"
        },
        {
            "name": "line2",
            "baseName": "line2",
            "type": "string"
        },
        {
            "name": "district",
            "baseName": "district",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ACHBillingDetails.attributeTypeMap;
    }
}

