/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ACHBillingDetails } from './aCHBillingDetails';
import { MetadataCardAndAch } from './metadataCardAndAch';

export class ACHCreationRequest {
    /**
    * Universally unique identifier (UUID v4) idempotency key. This key is utilized to ensure exactly-once execution of mutating requests.
    */
    'idempotencyKey': string;
    /**
    * The token for the ACH account provided by the processor (Plaid).
    */
    'plaidProcessorToken': string;
    'billingDetails': ACHBillingDetails;
    'metadata': MetadataCardAndAch;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idempotencyKey",
            "baseName": "idempotencyKey",
            "type": "string"
        },
        {
            "name": "plaidProcessorToken",
            "baseName": "plaidProcessorToken",
            "type": "string"
        },
        {
            "name": "billingDetails",
            "baseName": "billingDetails",
            "type": "ACHBillingDetails"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "MetadataCardAndAch"
        }    ];

    static getAttributeTypeMap() {
        return ACHCreationRequest.attributeTypeMap;
    }
}

