/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Indicates the failure reason of the ACH account. Only present on failed accounts. Possible values are [bank_account_authorization_expired, bank_account_error, bank_account_ineligible, bank_account_not_found, bank_account_unauthorized, unsupported_routing_number, verification_failed].
*/
export enum AchVerificationErrorCodes {
    BankAccountAuthorizationExpired = <any> 'bank_account_authorization_expired',
    BankAccountError = <any> 'bank_account_error',
    BankAccountIneligible = <any> 'bank_account_ineligible',
    BankAccountNotFound = <any> 'bank_account_not_found',
    BankAccountUnauthorized = <any> 'bank_account_unauthorized',
    UnsupportedRoutingNumber = <any> 'unsupported_routing_number',
    VerificationFailed = <any> 'verification_failed'
}
