/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';

/**
* Available and unsettled balances of the merchant.
*/
export class Balances {
    /**
    * List of currency balances (one for each currency) that are currently available to spend.
    */
    'available': Array<Money>;
    /**
    * List of currency balances (one for each currency) that have been captured but are currently in the process of settling and will become available to spend at some point in the future.
    */
    'unsettled': Array<Money>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "available",
            "baseName": "available",
            "type": "Array<Money>"
        },
        {
            "name": "unsettled",
            "baseName": "unsettled",
            "type": "Array<Money>"
        }    ];

    static getAttributeTypeMap() {
        return Balances.attributeTypeMap;
    }
}

