/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FiatMoneyUsd } from './fiatMoneyUsd';
import { PaymentInfoCancel } from './paymentInfoCancel';
import { PaymentInfoPaymentAndRefund } from './paymentInfoPaymentAndRefund';
import { PaymentStatus } from './paymentStatus';
import { RequiredAction } from './requiredAction';
import { SourceResponse } from './sourceResponse';

/**
* Status information of the related payment. This property is only present on refund or cancel items.
*/
export class BasicPayment {
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;
    /**
    * Type of the payment object.
    */
    'type': BasicPayment.TypeEnum;
    /**
    * Unique system generated identifier for the merchant.
    */
    'merchantId': string;
    /**
    * Unique system generated identifier for the wallet of the merchant.
    */
    'merchantWalletId'?: string;
    'amount': FiatMoneyUsd;
    'source': SourceResponse;
    /**
    * Enumerated description of the payment.
    */
    'description'?: BasicPayment.DescriptionEnum;
    'status': PaymentStatus;
    /**
    * Determines if a payment has successfully been captured. This property is only present for payments that did not use auto capture.
    */
    'captured'?: boolean;
    'captureAmount'?: FiatMoneyUsd;
    /**
    * ISO-8601 UTC date/time format.
    */
    'captureDate'?: string;
    'requiredAction'?: RequiredAction;
    'cancel'?: PaymentInfoCancel | null;
    'refunds'?: Array<PaymentInfoPaymentAndRefund>;
    'fees'?: FiatMoneyUsd;
    /**
    * The channel identifier that can be set for the payment. When not provided, the default channel is used.
    */
    'channel'?: string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate'?: string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BasicPayment.TypeEnum"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "merchantWalletId",
            "baseName": "merchantWalletId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "SourceResponse"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "BasicPayment.DescriptionEnum"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentStatus"
        },
        {
            "name": "captured",
            "baseName": "captured",
            "type": "boolean"
        },
        {
            "name": "captureAmount",
            "baseName": "captureAmount",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "captureDate",
            "baseName": "captureDate",
            "type": "string"
        },
        {
            "name": "requiredAction",
            "baseName": "requiredAction",
            "type": "RequiredAction"
        },
        {
            "name": "cancel",
            "baseName": "cancel",
            "type": "PaymentInfoCancel"
        },
        {
            "name": "refunds",
            "baseName": "refunds",
            "type": "Array<PaymentInfoPaymentAndRefund>"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BasicPayment.attributeTypeMap;
    }
}

export namespace BasicPayment {
    export enum TypeEnum {
        Payment = <any> 'payment'
    }
    export enum DescriptionEnum {
        Payment = <any> 'Payment'
    }
}
