/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FiatMoneyUsd } from './fiatMoneyUsd';

export class BasicChargebackHistory {
    /**
    * Enumerated type of the chargeback history event. `1st Chargeback` represents the first stage of the dispute procedure initiated by the cardholder’s issuing bank.   `2nd Chargeback` represents the second stage of the dispute procedure initiated by the cardholder’s issuing bank (This stage is MasterCard only).   `Chargeback Reversal` represents when 1st Chargeback or 2nd Chargeback is withdrawn by the issuer.   `Representment` represents the stage when merchants decided to dispute 1st Chargeback or 2nd Chargeback.   `Chargeback Settlement` can imply one of the two: 1) If merchant or marketplace is taking the lost of the chargeback, money will be debit from the wallet during this stage.   2) If merchant of marketplace successfully dispute the chargeback, money will be credit back to the wallet during this stage. 
    */
    'type': BasicChargebackHistory.TypeEnum;
    'chargebackAmount': FiatMoneyUsd;
    'fee'?: FiatMoneyUsd;
    /**
    * The reason the chargeback was created.
    */
    'description': string;
    /**
    * Unique system generated identifier for the settlement related to the chargeback history.
    */
    'settlementId'?: string | null;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BasicChargebackHistory.TypeEnum"
        },
        {
            "name": "chargebackAmount",
            "baseName": "chargebackAmount",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "settlementId",
            "baseName": "settlementId",
            "type": "string"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BasicChargebackHistory.attributeTypeMap;
    }
}

export namespace BasicChargebackHistory {
    export enum TypeEnum {
        _1stChargeback = <any> '1st Chargeback',
        _2ndChargeback = <any> '2nd Chargeback',
        ChargebackReversal = <any> 'Chargeback Reversal',
        Representment = <any> 'Representment',
        ChargebackSettlement = <any> 'Chargeback Settlement'
    }
}
