/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancelRefundReversalStatus } from './cancelRefundReversalStatus';
import { FiatMoneyUsd } from './fiatMoneyUsd';
import { PaymentInfoPaymentAndRefund } from './paymentInfoPaymentAndRefund';
import { SourceResponse } from './sourceResponse';

/**
* Status information of the related cancel. This property is only present on canceled payment or refund items.
*/
export class BasicCancel {
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;
    /**
    * Type of the payment object.
    */
    'type': BasicCancel.TypeEnum;
    /**
    * Unique system generated identifier for the merchant.
    */
    'merchantId': string;
    /**
    * Unique system generated identifier for the wallet of the merchant.
    */
    'merchantWalletId'?: string;
    'amount': FiatMoneyUsd;
    'source': SourceResponse;
    /**
    * Enumerated description of the payment.
    */
    'description'?: BasicCancel.DescriptionEnum;
    'status': CancelRefundReversalStatus;
    'originalPayment'?: PaymentInfoPaymentAndRefund;
    'fees'?: FiatMoneyUsd;
    /**
    * The channel identifier that can be set for the payment. When not provided, the default channel is used.
    */
    'channel'?: string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate'?: string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BasicCancel.TypeEnum"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "merchantWalletId",
            "baseName": "merchantWalletId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "SourceResponse"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "BasicCancel.DescriptionEnum"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CancelRefundReversalStatus"
        },
        {
            "name": "originalPayment",
            "baseName": "originalPayment",
            "type": "PaymentInfoPaymentAndRefund"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BasicCancel.attributeTypeMap;
    }
}

export namespace BasicCancel {
    export enum TypeEnum {
        Cancel = <any> 'cancel'
    }
    export enum DescriptionEnum {
        Payment = <any> 'Payment'
    }
}
