/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FiatMoney } from './fiatMoney';
import { FiatMoneyUsd } from './fiatMoneyUsd';
import { RiskEvaluation } from './riskEvaluation';
import { WalletLocation } from './walletLocation';

/**
* A deposit
*/
export class BusinessAccountDeposit {
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;
    /**
    * The identifier for the bank account where the funds were deposited from.
    */
    'sourceWalletId'?: string;
    'destination': WalletLocation;
    'amount': FiatMoney;
    'fee'?: FiatMoneyUsd;
    /**
    * Status of the deposit. Status `pending` indicates that the deposit is in the process of running; `complete` indicates it finished successfully; `failed` indicates it failed.
    */
    'status': BusinessAccountDeposit.StatusEnum;
    'riskEvaluation'?: RiskEvaluation | null;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate': string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "sourceWalletId",
            "baseName": "sourceWalletId",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "WalletLocation"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoney"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BusinessAccountDeposit.StatusEnum"
        },
        {
            "name": "riskEvaluation",
            "baseName": "riskEvaluation",
            "type": "RiskEvaluation"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BusinessAccountDeposit.attributeTypeMap;
    }
}

export namespace BusinessAccountDeposit {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Complete = <any> 'complete',
        Failed = <any> 'failed'
    }
}
