/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The destination bank account.
*/
export class BusinessAccountDestinationRequest {
    'type': BusinessAccountDestinationRequest.TypeEnum;
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BusinessAccountDestinationRequest.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BusinessAccountDestinationRequest.attributeTypeMap;
    }
}

export namespace BusinessAccountDestinationRequest {
    export enum TypeEnum {
        Wire = <any> 'wire',
        Sen = <any> 'sen'
    }
}
