/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BusinessAccountDestinationRequest } from './businessAccountDestinationRequest';
import { FiatMoney } from './fiatMoney';

export class BusinessAccountPayoutCreationRequest {
    /**
    * Universally unique identifier (UUID v4) idempotency key. This key is utilized to ensure exactly-once execution of mutating requests.
    */
    'idempotencyKey': string;
    'destination': BusinessAccountDestinationRequest;
    'amount': FiatMoney;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idempotencyKey",
            "baseName": "idempotencyKey",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "BusinessAccountDestinationRequest"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoney"
        }    ];

    static getAttributeTypeMap() {
        return BusinessAccountPayoutCreationRequest.attributeTypeMap;
    }
}

