/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CvvResults } from './cvvResults';

/**
* Indicates the status of the card for verification purposes.
*/
export class CardVerificationResponse {
    /**
    * Status of the AVS check. Raw AVS response, expressed as an upper-case letter. `not_requested` indicates check was not made. `pending` is pending/processing.
    */
    'avs': string;
    'cvv': CvvResults;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avs",
            "baseName": "avs",
            "type": "string"
        },
        {
            "name": "cvv",
            "baseName": "cvv",
            "type": "CvvResults"
        }    ];

    static getAttributeTypeMap() {
        return CardVerificationResponse.attributeTypeMap;
    }
}

