/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CardUpdate {
    /**
    * Universally unique identifier (UUID v4) of the public key used in encryption. NOTE the sandbox environment uses the default value of `key1`. For this reason the example supplied is `key1` rather than a UUID.
    */
    'keyId': string;
    /**
    * PGP encrypted base64 encoded string. Contains CVV. * **CVV (Card Verification Number)**: Three or four digit security code. REQUIRED\' 
    */
    'encryptedData': string;
    /**
    * Two digit number representing the card\'s expiration month.
    */
    'expMonth': number;
    /**
    * Four digit number representing the card\'s expiration year.
    */
    'expYear': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "keyId",
            "baseName": "keyId",
            "type": "string"
        },
        {
            "name": "encryptedData",
            "baseName": "encryptedData",
            "type": "string"
        },
        {
            "name": "expMonth",
            "baseName": "expMonth",
            "type": "number"
        },
        {
            "name": "expYear",
            "baseName": "expYear",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CardUpdate.attributeTypeMap;
    }
}

