/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ChannelResponse {
    /**
    * Unique system generated identifier for the entity.
    */
    'id'?: string;
    /**
    * Flag to indicate whether the channel is configured as default. At most one of the channels will have this flag set to true and the default channel is used when a payment request does not have the `channel` property set.
    */
    '_default'?: boolean;
    /**
    * Descriptor that appears on cardholders\' bank statements for card payments submitted through this channel.
    */
    'cardDescriptor'?: string;
    /**
    * Descriptor that appears on end-users\' bank statements for ACH payments submitted through this channel.
    */
    'achDescriptor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        },
        {
            "name": "cardDescriptor",
            "baseName": "cardDescriptor",
            "type": "string"
        },
        {
            "name": "achDescriptor",
            "baseName": "achDescriptor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChannelResponse.attributeTypeMap;
    }
}

