/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Enumerated category of the chargeback status codes based on the chargeback status code.
*/
export enum ChargebackCategories {
    CanceledRecurringPayment = <any> 'Canceled Recurring Payment',
    CustomerDispute = <any> 'Customer Dispute',
    Fraudulent = <any> 'Fraudulent',
    General = <any> 'General',
    ProcessingError = <any> 'Processing Error',
    NotDefined = <any> 'Not Defined'
}
