/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConfigurationPayments {
    /**
    * Unique system generated identifier for the wallet of the merchant.
    */
    'masterWalletId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "masterWalletId",
            "baseName": "masterWalletId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConfigurationPayments.attributeTypeMap;
    }
}

