/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A currency associated with a balance or address.
*/
export enum Currency {
    Usd = <any> 'USD',
    Eur = <any> 'EUR',
    Btc = <any> 'BTC',
    Eth = <any> 'ETH'
}
