/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BasicPayment } from './basicPayment';
import { CancelRefundReversalStatus } from './cancelRefundReversalStatus';
import { FiatMoneyUsd } from './fiatMoneyUsd';
import { MetadataPhoneEmail } from './metadataPhoneEmail';
import { PaymentErrorCode } from './paymentErrorCode';
import { RiskEvaluation } from './riskEvaluation';
import { SourceResponse } from './sourceResponse';

export class DetailedCancel {
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;
    /**
    * Type of the payment object.
    */
    'type': DetailedCancel.TypeEnum;
    /**
    * Unique system generated identifier for the merchant.
    */
    'merchantId': string;
    /**
    * Unique system generated identifier for the wallet of the merchant.
    */
    'merchantWalletId'?: string;
    'amount': FiatMoneyUsd;
    'source': SourceResponse;
    /**
    * Enumerated description of the payment.
    */
    'description'?: DetailedCancel.DescriptionEnum;
    'status': CancelRefundReversalStatus;
    'originalPayment'?: BasicPayment;
    'fees'?: FiatMoneyUsd;
    /**
    * Payment tracking reference. Will be present once known.
    */
    'trackingRef'?: string | null;
    'errorCode'?: PaymentErrorCode | null;
    'metadata'?: MetadataPhoneEmail;
    'riskEvaluation'?: RiskEvaluation | null;
    /**
    * If the cancel was made after a cutoff time period, it will be processed as a refund. This flag indicates that the cancel was processed as a refund\'
    */
    'refund'?: boolean = false;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate'?: string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DetailedCancel.TypeEnum"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "merchantWalletId",
            "baseName": "merchantWalletId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "SourceResponse"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "DetailedCancel.DescriptionEnum"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CancelRefundReversalStatus"
        },
        {
            "name": "originalPayment",
            "baseName": "originalPayment",
            "type": "BasicPayment"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "trackingRef",
            "baseName": "trackingRef",
            "type": "string"
        },
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "PaymentErrorCode"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "MetadataPhoneEmail"
        },
        {
            "name": "riskEvaluation",
            "baseName": "riskEvaluation",
            "type": "RiskEvaluation"
        },
        {
            "name": "refund",
            "baseName": "refund",
            "type": "boolean"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DetailedCancel.attributeTypeMap;
    }
}

export namespace DetailedCancel {
    export enum TypeEnum {
        Cancel = <any> 'cancel'
    }
    export enum DescriptionEnum {
        Payment = <any> 'Payment'
    }
}
