/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FiatMoneyUsd {
    /**
    * Magnitude of the amount, in units of the currency, with a `.`.
    */
    'amount': string;
    /**
    * Currency code.
    */
    'currency': FiatMoneyUsd.CurrencyEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "FiatMoneyUsd.CurrencyEnum"
        }    ];

    static getAttributeTypeMap() {
        return FiatMoneyUsd.attributeTypeMap;
    }
}

export namespace FiatMoneyUsd {
    export enum CurrencyEnum {
        Usd = <any> 'USD'
    }
}
