/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Stablecoin } from './stablecoin';

export class GetStablecoinsResponse {
    /**
    * A list of stablecoin objects containing its name, symbol, total amount, and per-chain amount.
    */
    'data'?: Array<Stablecoin>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Stablecoin>"
        }    ];

    static getAttributeTypeMap() {
        return GetStablecoinsResponse.attributeTypeMap;
    }
}

