/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Additional properties related to the payout beneficiary.
*/
export class MetadataPayout {
    /**
    * Email of the user.
    */
    'beneficiaryEmail': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "beneficiaryEmail",
            "baseName": "beneficiaryEmail",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MetadataPayout.attributeTypeMap;
    }
}

