/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FiatMoney } from './fiatMoney';
import { MockSenPaymentBeneficiaryBankInstruction } from './mockSenPaymentBeneficiaryBankInstruction';

export class MockSenPaymentRequest {
    /**
    * Circle tracking reference that needs to be set in the memo filed. This field is retrievable through the response during SEN account creation or via the bank instruction endpoint.
    */
    'trackingRef': string;
    'amount': FiatMoney;
    'beneficiaryBank': MockSenPaymentBeneficiaryBankInstruction;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trackingRef",
            "baseName": "trackingRef",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoney"
        },
        {
            "name": "beneficiaryBank",
            "baseName": "beneficiaryBank",
            "type": "MockSenPaymentBeneficiaryBankInstruction"
        }    ];

    static getAttributeTypeMap() {
        return MockSenPaymentRequest.attributeTypeMap;
    }
}

