/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FiatMoneyUsd } from './fiatMoneyUsd';
import { MockAchAccount } from './mockAchAccount';

export class MockAchAccountResponse {
    /**
    * The processor token needs to be provided when linking an ACH account against this mock.
    */
    'processorToken'?: string;
    'balance'?: FiatMoneyUsd;
    'account'?: MockAchAccount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "processorToken",
            "baseName": "processorToken",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "MockAchAccount"
        }    ];

    static getAttributeTypeMap() {
        return MockAchAccountResponse.attributeTypeMap;
    }
}

