/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Enumerated status of the check. `pass` indicates successful 3DS authentication. `fail` indicates failed 3DS authentication.
*/
export enum Model3dsResults {
    Pass = <any> 'pass',
    Fail = <any> 'fail'
}
