/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancelRefundReversalStatus } from './cancelRefundReversalStatus';

/**
* Status information of the related cancel. This property is only present on canceled payment or refund items.
*/
export class PaymentInfoCancel {
    /**
    * Unique system generated identifier for the entity.
    */
    'id'?: string;
    /**
    * Type of the payment object.
    */
    'type'?: PaymentInfoCancel.TypeEnum;
    /**
    * Enumerated description of the payment item.
    */
    'description'?: PaymentInfoCancel.DescriptionEnum;
    'status'?: CancelRefundReversalStatus;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentInfoCancel.TypeEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "PaymentInfoCancel.DescriptionEnum"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CancelRefundReversalStatus"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentInfoCancel.attributeTypeMap;
    }
}

export namespace PaymentInfoCancel {
    export enum TypeEnum {
        Cancel = <any> 'cancel'
    }
    export enum DescriptionEnum {
        Payment = <any> 'Payment'
    }
}
