/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Indicates the failure reason of a payment. Only present for payments in failed state. Possible values are [`payment_failed`, `payment_fraud_detected`, `payment_denied`, `payment_not_supported_by_issuer`, `payment_not_funded`, `payment_unprocessable`, `payment_stopped_by_issuer`, `payment_canceled`, `payment_returned`, `payment_failed_balance_check`, `card_failed`, `card_invalid`, `card_address_mismatch`, `card_zip_mismatch`, `card_cvv_invalid`, `card_expired`, `card_limit_violated`, `card_not_honored`, `card_cvv_required`, `credit_card_not_allowed`, `card_account_ineligible`, `card_network_unsupported`, `channel_invalid`, `unauthorized_transaction`, `bank_account_ineligible`, `bank_transaction_error`, `invalid_account_number`, `invalid_wire_rtn`, `invalid_ach_rtn`, `vendor_inactive`]\'
*/
export enum PaymentErrorCode {
    PaymentFailed = <any> 'payment_failed',
    PaymentFraudDetected = <any> 'payment_fraud_detected',
    PaymentDenied = <any> 'payment_denied',
    PaymentNotSupportedByIssuer = <any> 'payment_not_supported_by_issuer',
    PaymentNotFunded = <any> 'payment_not_funded',
    PaymentUnprocessable = <any> 'payment_unprocessable',
    PaymentStoppedByIssuer = <any> 'payment_stopped_by_issuer',
    PaymentCanceled = <any> 'payment_canceled',
    PaymentReturned = <any> 'payment_returned',
    PaymentFailedBalanceCheck = <any> 'payment_failed_balance_check',
    CardFailed = <any> 'card_failed',
    CardInvalid = <any> 'card_invalid',
    CardAddressMismatch = <any> 'card_address_mismatch',
    CardZipMismatch = <any> 'card_zip_mismatch',
    CardCvvInvalid = <any> 'card_cvv_invalid',
    CardExpired = <any> 'card_expired',
    CardLimitViolated = <any> 'card_limit_violated',
    CardNotHonored = <any> 'card_not_honored',
    CardCvvRequired = <any> 'card_cvv_required',
    CardRestricted = <any> 'card_restricted,',
    CardAccountIneligible = <any> 'card_account_ineligible',
    CardNetworkUnsupported = <any> 'card_network_unsupported',
    ChannelInvalid = <any> 'channel_invalid',
    UnauthorizedTransaction = <any> 'unauthorized_transaction',
    BankAccountIneligible = <any> 'bank_account_ineligible',
    BankTransactionError = <any> 'bank_transaction_error',
    InvalidAccountNumber = <any> 'invalid_account_number',
    InvalidWireRtn = <any> 'invalid_wire_rtn',
    InvalidAchRtn = <any> 'invalid_ach_rtn',
    RefIdInvalid = <any> 'ref_id_invalid',
    AccountNameMismatch = <any> 'account_name_mismatch',
    AccountNumberMismatch = <any> 'account_number_mismatch',
    AccountIneligible = <any> 'account_ineligible',
    WalletAddressMismatch = <any> 'wallet_address_mismatch',
    CustomerNameMismatch = <any> 'customer_name_mismatch',
    InstitutionNameMismatch = <any> 'institution_name_mismatch',
    VendorInactive = <any> 'vendor_inactive'
}
