/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FiatMoneyUsd } from './fiatMoneyUsd';
import { PaymentStatus } from './paymentStatus';
import { RequiredAction } from './requiredAction';

/**
* Status information of the related payment. This property is only present on refund or cancel items.
*/
export class PaymentInfoPaymentAndRefund {
    /**
    * Unique system generated identifier for the entity.
    */
    'id'?: string;
    /**
    * Type of the payment object.
    */
    'type'?: PaymentInfoPaymentAndRefund.TypeEnum;
    'amount'?: FiatMoneyUsd;
    /**
    * Enumerated description of the payment item.
    */
    'description'?: PaymentInfoPaymentAndRefund.DescriptionEnum;
    'status'?: PaymentStatus;
    'requiredAction'?: RequiredAction;
    'fees'?: FiatMoneyUsd;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentInfoPaymentAndRefund.TypeEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "PaymentInfoPaymentAndRefund.DescriptionEnum"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentStatus"
        },
        {
            "name": "requiredAction",
            "baseName": "requiredAction",
            "type": "RequiredAction"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentInfoPaymentAndRefund.attributeTypeMap;
    }
}

export namespace PaymentInfoPaymentAndRefund {
    export enum TypeEnum {
        Payment = <any> 'payment',
        Refund = <any> 'refund'
    }
    export enum DescriptionEnum {
        Payment = <any> 'Payment'
    }
}
