/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The destination bank account type.
*/
export enum PayoutDestinationType {
    Wire = <any> 'wire',
    Ach = <any> 'ach',
    Sepa = <any> 'sepa'
}
