/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancelRefundReversalStatus } from './cancelRefundReversalStatus';
import { FiatMoneyUsd } from './fiatMoneyUsd';
import { ReversalReason } from './reversalReason';

export class Reversal {
    /**
    * Universally unique identifier (UUID v4) of the public key used in encryption. NOTE the sandbox environment uses the default value of `key1`. For this reason the example supplied is `key1` rather than a UUID.
    */
    'id': string;
    /**
    * Unique system generated identifier for the payment that is associated to the chargeback item.
    */
    'paymentId': string;
    'amount': FiatMoneyUsd;
    /**
    * Enumerated description of the payment.
    */
    'description': string;
    'status': CancelRefundReversalStatus;
    'reason': ReversalReason;
    'fees': FiatMoneyUsd;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate': string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CancelRefundReversalStatus"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "ReversalReason"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Reversal.attributeTypeMap;
    }
}

