/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Enumerated reason for a returned payment. Providing this reason in the request is recommended (to improve risk evaluation) but not required.
*/
export enum ReversalReason {
    Duplicate = <any> 'duplicate',
    Fraudulent = <any> 'fraudulent',
    RequestedByCustomer = <any> 'requested_by_customer',
    BankTransactionError = <any> 'bank_transaction_error',
    InvalidAccountNumber = <any> 'invalid_account_number',
    InsufficientFunds = <any> 'insufficient_funds',
    PaymentStoppedByIssuer = <any> 'payment_stopped_by_issuer',
    PaymentReturned = <any> 'payment_returned',
    BankAccountIneligible = <any> 'bank_account_ineligible',
    InvalidAchRtn = <any> 'invalid_ach_rtn',
    UnauthorizedTransaction = <any> 'unauthorized_transaction',
    PaymentFailed = <any> 'payment_failed'
}
