/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExternalFiatAccountStatus } from './externalFiatAccountStatus';

export class SenFiatAccountResponse {
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;
    'status': ExternalFiatAccountStatus;
    /**
    * Bank name plus last four digits of the bank account number.
    */
    'description': string;
    /**
    * Circle tracking reference that needs to be set in the memo field..
    */
    'trackingRef': string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate': string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate': string;
    /**
    * Currency of the fiat account.
    */
    'currency'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ExternalFiatAccountStatus"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "trackingRef",
            "baseName": "trackingRef",
            "type": "string"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SenFiatAccountResponse.attributeTypeMap;
    }
}

