/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SEPAInstructionBeneficiary } from './sEPAInstructionBeneficiary';
import { SEPAInstructionBeneficiaryBank } from './sEPAInstructionBeneficiaryBank';

export class SEPAInstruction {
    /**
    * Circle tracking reference that needs to be set in the SEPA transfer reference field.
    */
    'trackingRef'?: string;
    'beneficiary'?: SEPAInstructionBeneficiary;
    'beneficiaryBank'?: SEPAInstructionBeneficiaryBank;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trackingRef",
            "baseName": "trackingRef",
            "type": "string"
        },
        {
            "name": "beneficiary",
            "baseName": "beneficiary",
            "type": "SEPAInstructionBeneficiary"
        },
        {
            "name": "beneficiaryBank",
            "baseName": "beneficiaryBank",
            "type": "SEPAInstructionBeneficiaryBank"
        }    ];

    static getAttributeTypeMap() {
        return SEPAInstruction.attributeTypeMap;
    }
}

