/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FiatMoneyUsd } from './fiatMoneyUsd';

export class Settlement {
    /**
    * Unique system generated identifier for the entity.
    */
    'id'?: string;
    /**
    * Unique system generated identifier for the wallet of the merchant.
    */
    'merchantWalletId'?: string;
    /**
    * If this settlement was used for a marketplace payment, the wallet involved in the settlement. Not included for standard merchant settlements.
    */
    'walletId'?: string;
    'totalDebits'?: FiatMoneyUsd;
    'totalCredits'?: FiatMoneyUsd;
    'paymentFees'?: FiatMoneyUsd;
    'chargebackFees'?: FiatMoneyUsd;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate'?: string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merchantWalletId",
            "baseName": "merchantWalletId",
            "type": "string"
        },
        {
            "name": "walletId",
            "baseName": "walletId",
            "type": "string"
        },
        {
            "name": "totalDebits",
            "baseName": "totalDebits",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "totalCredits",
            "baseName": "totalCredits",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "paymentFees",
            "baseName": "paymentFees",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "chargebackFees",
            "baseName": "chargebackFees",
            "type": "FiatMoneyUsd"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Settlement.attributeTypeMap;
    }
}

