/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SignetInstruction {
    /**
    * Circle tracking reference that needs to be set in the signet public description field.
    */
    'trackingRef'?: string;
    /**
    * Circle wallet address that needs to be set in the signet recipient wallet field.
    */
    'walletAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trackingRef",
            "baseName": "trackingRef",
            "type": "string"
        },
        {
            "name": "walletAddress",
            "baseName": "walletAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SignetInstruction.attributeTypeMap;
    }
}

