/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExternalFiatAccountStatus } from './externalFiatAccountStatus';

export class SignetFiatAccountResponse {
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;
    'status': ExternalFiatAccountStatus;
    /**
    * Tracking ref that needs to be set in the public description field when you send the funds to Circle Signet wallet.
    */
    'trackingRef': string;
    /**
    * Your signet wallet address.
    */
    'walletAddress': string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate': string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ExternalFiatAccountStatus"
        },
        {
            "name": "trackingRef",
            "baseName": "trackingRef",
            "type": "string"
        },
        {
            "name": "walletAddress",
            "baseName": "walletAddress",
            "type": "string"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SignetFiatAccountResponse.attributeTypeMap;
    }
}

