/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The payment source.
*/
export class SourceResponse {
    /**
    * Unique system generated identifier for the entity.
    */
    'id'?: string;
    /**
    * Type of the source.
    */
    'type'?: SourceResponse.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SourceResponse.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return SourceResponse.attributeTypeMap;
    }
}

export namespace SourceResponse {
    export enum TypeEnum {
        Card = <any> 'card',
        Ach = <any> 'ach',
        Wire = <any> 'wire',
        Sepa = <any> 'sepa'
    }
}
