/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TokenAmount } from './tokenAmount';

export class Stablecoin {
    /**
    * Name of the stablecoin.
    */
    'name'?: string;
    /**
    * Symbol of the stablecoin.
    */
    'symbol'?: string;
    /**
    * Total circulating amount of the stablecoin.
    */
    'totalAmount'?: string;
    /**
    * A list of the broken down totalAmount by chain of the stablecoin.
    */
    'chains'?: Array<TokenAmount>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "totalAmount",
            "baseName": "totalAmount",
            "type": "string"
        },
        {
            "name": "chains",
            "baseName": "chains",
            "type": "Array<TokenAmount>"
        }    ];

    static getAttributeTypeMap() {
        return Stablecoin.attributeTypeMap;
    }
}

