/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionDetail {
    /**
    * Identifier for created subscription.
    */
    'url'?: string;
    /**
    * Status of the subscription request.
    */
    'status'?: SubscriptionDetail.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SubscriptionDetail.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionDetail.attributeTypeMap;
    }
}

export namespace SubscriptionDetail {
    export enum StatusEnum {
        Confirmed = <any> 'confirmed',
        Pending = <any> 'pending',
        Deleted = <any> 'deleted'
    }
}
