/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TransferRequestVerifiedBlockchainLocation {
    'type': TransferRequestVerifiedBlockchainLocation.TypeEnum;
    /**
    * The ID of the verified blockchain recipient address.
    */
    'addressId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TransferRequestVerifiedBlockchainLocation.TypeEnum"
        },
        {
            "name": "addressId",
            "baseName": "addressId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransferRequestVerifiedBlockchainLocation.attributeTypeMap;
    }
}

export namespace TransferRequestVerifiedBlockchainLocation {
    export enum TypeEnum {
        VerifiedBlockchain = <any> 'verified_blockchain'
    }
}
