/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Chain } from './chain';
import { Identity } from './identity';
import { TransferSourceBlockchainLocation } from './transferSourceBlockchainLocation';
import { TransferSourceWalletLocation } from './transferSourceWalletLocation';

/**
* A source of funds.
*/
export class TransferSourceLocation {
    'type': TransferSourceLocation.TypeEnum;
    /**
    * The id of the wallet.
    */
    'id': string;
    'identities'?: Array<Identity>;
    'chain': Chain;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TransferSourceLocation.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "identities",
            "baseName": "identities",
            "type": "Array<Identity>"
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "Chain"
        }    ];

    static getAttributeTypeMap() {
        return TransferSourceLocation.attributeTypeMap;
    }
}

export namespace TransferSourceLocation {
    export enum TypeEnum {
        Blockchain = <any> 'blockchain'
    }
}
