/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A destination wallet location.
*/
export class TransferDestinationWalletLocation {
    'type': TransferDestinationWalletLocation.TypeEnum;
    /**
    * The id of the wallet.
    */
    'id': string;
    /**
    * An alphanumeric string which indicates the wallet address used to receive the transfer. Will only be set when the transfer source is a blockchain address.
    */
    'address'?: string;
    /**
    * The secondary identifier for a blockchain address. An example of this is the memo field on the Stellar network, which can be text, id, or hash format.
    */
    'addressTag'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TransferDestinationWalletLocation.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "addressTag",
            "baseName": "addressTag",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransferDestinationWalletLocation.attributeTypeMap;
    }
}

export namespace TransferDestinationWalletLocation {
    export enum TypeEnum {
        Wallet = <any> 'wallet'
    }
}
