/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';
import { TransferCreationRequestDestination } from './transferCreationRequestDestination';
import { TransferRequestSourceWalletLocation } from './transferRequestSourceWalletLocation';

export class TransferCreationRequest {
    /**
    * Universally unique identifier (UUID v4) idempotency key. This key is utilized to ensure exactly-once execution of mutating requests.
    */
    'idempotencyKey': string;
    'source': TransferRequestSourceWalletLocation;
    'destination': TransferCreationRequestDestination;
    'amount': Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idempotencyKey",
            "baseName": "idempotencyKey",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "TransferRequestSourceWalletLocation"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "TransferCreationRequestDestination"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return TransferCreationRequest.attributeTypeMap;
    }
}

