/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Identity } from './identity';

/**
* A source wallet location.
*/
export class TransferSourceWalletLocation {
    'type': TransferSourceWalletLocation.TypeEnum;
    /**
    * The id of the wallet.
    */
    'id': string;
    'identities'?: Array<Identity>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TransferSourceWalletLocation.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "identities",
            "baseName": "identities",
            "type": "Array<Identity>"
        }    ];

    static getAttributeTypeMap() {
        return TransferSourceWalletLocation.attributeTypeMap;
    }
}

export namespace TransferSourceWalletLocation {
    export enum TypeEnum {
        Wallet = <any> 'wallet'
    }
}
