/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Indicates the failure reason of the card verification. Only present on cards with failed verification. Possible values are [verification_failed, verification_fraud_detected, verification_denied, verification_not_supported_by_issuer, verification_stopped_by_issuer, card_failed, card_invalid, card_address_mismatch, card_zip_mismatch, card_cvv_invalid, card_expired, card_limit_violated, card_not_honored, card_cvv_required, credit_card_not_allowed, card_account_ineligible, card_network_unsupported]\'
*/
export enum VerificationErrorCode {
    VerificationFailed = <any> 'verification_failed',
    VerificationFraudDetected = <any> 'verification_fraud_detected',
    VerificationDenied = <any> 'verification_denied',
    VerificationNotSupportedByIssuer = <any> 'verification_not_supported_by_issuer',
    VerificationStoppedByIssuer = <any> 'verification_stopped_by_issuer',
    CardFailed = <any> 'card_failed',
    CardInvalid = <any> 'card_invalid',
    CardAddressMismatch = <any> 'card_address_mismatch',
    CardZipMismatch = <any> 'card_zip_mismatch',
    CardCvvInvalid = <any> 'card_cvv_invalid',
    CardExpired = <any> 'card_expired',
    CardLimitViolated = <any> 'card_limit_violated',
    CardNotHonored = <any> 'card_not_honored',
    CardCvvRequired = <any> 'card_cvv_required',
    CreditCardNotAllowed = <any> 'credit_card_not_allowed',
    CardAccountIneligible = <any> 'card_account_ineligible',
    CardNetworkUnsupported = <any> 'card_network_unsupported'
}
