/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';

export class Wallet {
    /**
    * Wallet identifier. Numeric value but should be treated as a string as format may change in the future\'
    */
    'walletId'?: string;
    /**
    * Universally unique identifier (UUID v4) of the entity that owns the wallet.
    */
    'entityId'?: string;
    /**
    * Wallet type.
    */
    'type'?: Wallet.TypeEnum;
    /**
    * A human-friendly, non-unique identifier for a wallet.
    */
    'description'?: string;
    /**
    * A list of balances for currencies owned by the wallet.
    */
    'balances'?: Array<Money>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "walletId",
            "baseName": "walletId",
            "type": "string"
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Wallet.TypeEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "balances",
            "baseName": "balances",
            "type": "Array<Money>"
        }    ];

    static getAttributeTypeMap() {
        return Wallet.attributeTypeMap;
    }
}

export namespace Wallet {
    export enum TypeEnum {
        EndUserWallet = <any> 'end_user_wallet'
    }
}
