/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WireInstructionBeneficiaryBank {
    /**
    * Name of the beneficiary\'s bank.
    */
    'name'?: string;
    /**
    * SWIFT code of the beneficiary\'s bank account.
    */
    'swiftCode'?: string;
    /**
    * ABA Routing number of the beneficiary\'s bank account.
    */
    'routingNumber'?: string;
    /**
    * Account number of the beneficiary\'s bank account.
    */
    'accountNumber'?: string;
    /**
    * Currency of the beneficiary\'s bank account.
    */
    'currency'?: string;
    /**
    * Address of the beneficiary\'s bank.
    */
    'address'?: string;
    /**
    * City of the beneficiary\'s bank.
    */
    'city'?: string;
    /**
    * Postal code of the beneficiary\'s bank.
    */
    'postalCode'?: string;
    /**
    * Country code of the beneficiary\'s bank. Formatted as a two-letter country code specified in ISO 3166-1 alpha-2.
    */
    'country'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "swiftCode",
            "baseName": "swiftCode",
            "type": "string"
        },
        {
            "name": "routingNumber",
            "baseName": "routingNumber",
            "type": "string"
        },
        {
            "name": "accountNumber",
            "baseName": "accountNumber",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WireInstructionBeneficiaryBank.attributeTypeMap;
    }
}

