/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BankAddressNonIban } from './bankAddressNonIban';
import { BillingDetails } from './billingDetails';
import { WireCreationRequestAccountNumber } from './wireCreationRequestAccountNumber';
import { WireCreationRequestIban } from './wireCreationRequestIban';
import { WireCreationRequestUS } from './wireCreationRequestUS';

/**
* Request object used to create a bank account (wires). Different fields are required depending on the bank country, see the guide documentation for the list of supported bank countries along with which ones support IBAN.
*/
export class WireCreationRequest {
    /**
    * Universally unique identifier (UUID v4) idempotency key. This key is utilized to ensure exactly-once execution of mutating requests.
    */
    'idempotencyKey': string;
    /**
    * Account number that identifies the bank account.
    */
    'accountNumber': string;
    /**
    * The bank\'s SWIFT / BIC code.
    */
    'routingNumber': string;
    'billingDetails': BillingDetails;
    'bankAddress': BankAddressNonIban;
    /**
    * International Bank Account Number (IBAN) for the bank account.
    */
    'iban': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idempotencyKey",
            "baseName": "idempotencyKey",
            "type": "string"
        },
        {
            "name": "accountNumber",
            "baseName": "accountNumber",
            "type": "string"
        },
        {
            "name": "routingNumber",
            "baseName": "routingNumber",
            "type": "string"
        },
        {
            "name": "billingDetails",
            "baseName": "billingDetails",
            "type": "BillingDetails"
        },
        {
            "name": "bankAddress",
            "baseName": "bankAddress",
            "type": "BankAddressNonIban"
        },
        {
            "name": "iban",
            "baseName": "iban",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WireCreationRequest.attributeTypeMap;
    }
}

