/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BankAddress } from './bankAddress';
import { BillingDetails } from './billingDetails';
import { ExternalFiatAccountStatus } from './externalFiatAccountStatus';

export class Wire {
    /**
    * Unique system generated identifier for the entity.
    */
    'id': string;
    'status': ExternalFiatAccountStatus;
    /**
    * Bank name plus last four digits of the bank account number or IBAN.
    */
    'description': string;
    /**
    * Wire tracking ref that needs to be set in the wire reference to beneficiary field.
    */
    'trackingRef': string;
    /**
    * A UUID that uniquely identifies the account number. If the same account is used more than once, each card object will have a different id, but the fingerprint will stay the same.
    */
    'fingerprint': string;
    'billingDetails': BillingDetails;
    'bankAddress'?: BankAddress;
    /**
    * ISO-8601 UTC date/time format.
    */
    'createDate': string;
    /**
    * ISO-8601 UTC date/time format.
    */
    'updateDate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ExternalFiatAccountStatus"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "trackingRef",
            "baseName": "trackingRef",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "billingDetails",
            "baseName": "billingDetails",
            "type": "BillingDetails"
        },
        {
            "name": "bankAddress",
            "baseName": "bankAddress",
            "type": "BankAddress"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Wire.attributeTypeMap;
    }
}

