/**
 * Core Functionality
 * APIs for managing your account balance. These endpoints are available with all Circle APIs.
 *
 * The version of the OpenAPI document: ${version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BankAddress } from './bankAddress';
import { BillingDetails } from './billingDetails';

/**
* Relevant fields for U.S. bank accounts.
*/
export class WireCreationRequestUS {
    /**
    * Universally unique identifier (UUID v4) idempotency key. This key is utilized to ensure exactly-once execution of mutating requests.
    */
    'idempotencyKey': string;
    /**
    * Account number that identifies the bank account.
    */
    'accountNumber': string;
    /**
    * ABA routing number for the bank account. Note this has to be specific for bank wire transfers.
    */
    'routingNumber': string;
    'billingDetails': BillingDetails;
    'bankAddress': BankAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idempotencyKey",
            "baseName": "idempotencyKey",
            "type": "string"
        },
        {
            "name": "accountNumber",
            "baseName": "accountNumber",
            "type": "string"
        },
        {
            "name": "routingNumber",
            "baseName": "routingNumber",
            "type": "string"
        },
        {
            "name": "billingDetails",
            "baseName": "billingDetails",
            "type": "BillingDetails"
        },
        {
            "name": "bankAddress",
            "baseName": "bankAddress",
            "type": "BankAddress"
        }    ];

    static getAttributeTypeMap() {
        return WireCreationRequestUS.attributeTypeMap;
    }
}

