# This workflow will run tests using node and then publish a package to npm
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to npm

on: [workflow_dispatch, workflow_call]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: github-hosted-small
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn run test

  publish-npm:
    needs: build
    runs-on: github-hosted-small
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.com/
      - run: yarn install --frozen-lockfile
      - run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_PAY }}:role/github-actions-service-role

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: aws-actions/aws-secretsmanager-get-secrets@2cb1a461cbd4865ac4299648312e4704c646cd53 # v3.0.1
        with:
          secret-ids: |
            /prod/circle-nodejs-sdk/npm/automation-token

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ env._PROD_CIRCLE_NODEJS_SDK_NPM_AUTOMATION_TOKEN }}
